### ISSUE TITLE
"aware" of code in source_documents?

### ISSUE THREAD

**Issue by mcchung52** [imartinez/privateGPT#1000]
I'm trying to have this thing analyze on or refer to a code repo. I git cloned the repo into source_documents and added more file parsers (as text) with extensions like .java, .yml. Ingestion seemed to work. But when I now ask questions about it, it isn't aware of it. Is there like a trigger word or something to act on it or make it be aware of it? I do get "sources" from files in the repo though.

**Comment by DenizOrsel** [comment]
I very much think you are running into token limits so that LLM is unaware of the rest of the content even if ingestion is executed correct. I am afraid you may not get around it until billion tokens become a thing. And yeah that pretty much renders it useless. Your only other option is to really train your data and come up with a specialized set.
