### ISSUE TITLE
Local server configuration for external llama-cpp-server api 

### ISSUE THREAD

**Issue by uninstallit** [imartinez/privateGPT#1194]
I was reading the documentation and I noticed that PrivateGPT can be configured with Open AI by specifying a key, etc.

However, I was thinking If I have `llama-cpp-server` running with Llama-2, and their server I believe follows the OpenAI api - is it perhaps possible to proxy the OpenAI domain and redirect it to the local server.

The llama-cpp-server has these endpoints among a few others:

```
- /v1/completions
- /v1/embeddings
- /v1/chat/completions
```

Do you think this is feasible? Also would be really nice if it supported some configuration for a generic server.

**Comment by pabloogc** [comment]
I think we are quite far from a standard LLM API definition (it will probably never happen) and I would not consider using llama-cpp as a proxy. If you want to go that route adding a custom  LLM implementation to llama-index makes more sense. 

On that topic, we took and extended openai schema because it's well designed and a lot of people are used to their naming conventions. Looks like Llama-cpp did too but I think it's too early to generalize.

I'll close the issue to try to keep the repo tidy, thanks for sharing your thoughts.
