### ISSUE TITLE
when i poetry run scripts/setup No module named private_gpt

### ISSUE THREAD

**Issue by ticticpm** [imartinez/privateGPT#1282]
\privateGPT\scripts\setup", line 7, in <module>
    from private_gpt.paths import models_path, models_cache_path
ModuleNotFoundError: No module named 'private_gpt'

What do i do??

**Comment by lopagela** [comment]
@ticticpm this error is caused because you are trying to launch this script while "being at the wrong place".

You need to run this script from the root of `privateGPT` repository.

I never used windows shell, but it should be something like that (be sure to use the correct python ! You have to use the python environment in which all your libraries are installed)
```shell
cd privateGPT

python scripts\setup
```

**Comment by ticticpm** [comment]
Hello! I **poetry install**
and then it worked

Thank you for a swift reply, though!
