### ISSUE TITLE
Response not getting complete

### ISSUE THREAD

**Issue by aniketkhajanchi** [imartinez/privateGPT#1299]
I updated the CTX to 2048 but still the response length dosen't change. It turns out incomplete. 
Is there a timeout or something that restricts the responses to complete
If someone got this sorted please let me know.

**Comment by kalle07** [comment]
only 1200 charcters at max ...

**Comment by mrbeandev** [comment]
is there anyway to increase this ?
i am trying to finish a code for testing the model

Prompt : ``create a html code of a calculator with all functions of a normal calculator and use bootstrap and jquery. give me full code``

Response : 
```
Here is an example of a simple HTML, CSS, and JavaScript code for a calculator using Bootstrap and jQuery:


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Simple Calculator</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl7/1L_dstPt3HV5HzF6Gvk/e9T9hXmJ58bldgTk+" crossorigin="anonymous" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!--
```

its always stopping here , very annoying 🤣

**Comment by seanmavley** [comment]
Enter `continue` in the chat, and the generation will continue from where it stopped

**Comment by aniketkhajanchi** [comment]
> Enter `continue` in the chat, and the generation will continue from where it stopped

I am using the primoridal version and this dosent work

**Comment by mrbeandev** [comment]
> Enter `continue` in the chat, and the generation will continue from where it stopped

what ?
is there a continue option in privateGPT UI ?? 😮

**Comment by aniketkhajanchi** [comment]
In the new version of privateGPT, there is an option to change configuration of the llm (max_new_tokens)
where do i exactly change this in the primordial version.

**Comment by kalle07** [comment]
again   ;)

only 1200 charcters at max ...

**Comment by kalle07** [comment]
i found:
```
llm:
  mode: local
```

3 times , 2 times in settings and once in settings-lcoal
i added max_new_tokens: 1024

nothing change ...  ;)
Why do you force the good programme to write only a few lines?
i updated it a week ago

**Comment by lopagela** [comment]
@kalle07 
On what version are you (which git commit)?

Please use the default configuration file (`settings.yaml`) only (no other profile), and can you copy paste your full `settings.yaml`?

Can you also share the 2 or 3 first logs you have after starting your privateGPT.

**Comment by kalle07** [comment]
@lopagela

Hi ...
i have reinstalled all new on windows inside the privatgpt installation folder
git reset --hard 
and i then start with
git pull
than i leave install penv and make (hope its ok)
than:
poetry install --with ui
poetry install --with local
poetry run python scripts/setup
$env:CMAKE_ARGS='-DLLAMA_CUBLAS=on'; poetry run pip install --force-reinstall --no-cache-dir llama-cpp-python

all running without errors!
i start, all ok!
10:31:22.605 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
10:31:24.437 [INFO    ] private_gpt.components.llm.llm_component - Initializing the LLM in mode=local
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4060 Ti, compute capability 8.9
llama_model_loader: loaded meta data with 20 key-value pairs and 291 tensors from E:\privateGPT\models\mistral-7b-instruct-v0.1.Q4_K_M.gguf (version GGUF V2)

if i ask somewhat the response is very slow (5tokens/s), if i press "stop" after 5 words after 5sec 1800characters i see in the powershell, so a long story AND this 2times once with [/INST] at start?

OMG what is wrong ?  ^^

**Comment by lopagela** [comment]
`pyenv` and `make` binaries should be left intact indeed. However, did you created a new and clean python virtual env? (through either `pyenv`, `conda`, or `python -m venv` ?

From what I see in your logs, your GPU is being correctly detected and you are using CUDA, which is good.

Going back to the initial issue, from what I see in the logs, only your file `settings.yaml` is being loaded. You still did not shared this file (so that I can verify if you setup the proper configuration).

Re inference speed: the `stream = true` mode is slower than the `stream = false` mode. In other words, if you really want speed, you should be using `privateGPT` through it's HTTP API instead (see the API reference in our documentation).

https://docs.privategpt.dev/api-reference

----

So far as I am aware of, the issue seems to be your local installation, and not `privateGPT` implementation. Can you please carefully read the documentation to try and troubleshoot your issue?
If, during your investigation, you think you found some error in our implementation that is actually causing you hot burns, please open a new issue.
