### ISSUE TITLE
delete ingested optimization

### ISSUE THREAD

**Issue by quincy451** [imartinez/privateGPT#1395]
I have a pdf file with 250 pages.  It is ingested as 250 page references with 250 different document ID's.  If I ingest the doucment again, I get twice as many page refernces.  I would like the ablity to delete all page references to a given file_name in one API call.  RIght now I write out all 250 page's document ID's and have python code read in each one from a file and delete each one...but it can take an hour to delete 250 pages, if the api call did it in one call it would be much quicker.

**Comment by airtonix** [comment]
https://github.com/imartinez/privateGPT/issues/1342#issuecomment-1837043079

is this what you're doing ?

**Comment by quincy451** [comment]
no I am using https://docs.privategpt.dev/api-reference/api-reference/ingestion/delete-ingestedI want to be able to delete an entire document quickly but leave x number of other documents still present.  The link you point to would wipe all documents.  
    On Wednesday, December 13, 2023 at 12:48:54 AM CST, Zeno Jiricek ***@***.***> wrote:  
 
 


#1342 (comment)

is this what you're doing ?

**Comment by croossin** [comment]
+1 would be nice from UI if you can just delete that ingested doc (and it will take care of deleting all documentIds)

**Comment by vhminhquan** [comment]
i found many topics for this issue . But noone could help. It's so hard

**Comment by quincy451** [comment]
found a workaround...don't import a pdf, import a .docx file...and install the docxtotxt module with pip install docxtotxt to make that work.  Deletion is much faster.

**Comment by herkul24** [comment]
In my case, the deleting of Ingested files takes extreme time. During the ingesting process (embedding) due to parallelization my 32 Threads can be utilized fully at 100% which makes this process enough fast, so that it is acceptable. But if I try to delete an ingested file, it takes very long time, because the CPU utilization is almost below 5%. One of the main reason is a cancelled upload, since sometimes in case the upload faces issues or takes long time the upload will be cancelled. If I try to re-upload this file, privateGPT tries first to delete this file and re-index all files. This is very annoying, since it can take even many days, which is unacceptable. Is there any solution regarding this problem?
