### ISSUE TITLE
Group(s) not found: local (via --with), ui (via --with)

### ISSUE THREAD

**Issue by mictadlo** [imartinez/privateGPT#1737]
Hi @imartinez and @mberman84,
I try to install privateGPT but I ran into this problem on a MacBook pro M1:
```
git clone https://github.com/imartinez/privateGPT
cd privateGPT

conda create -n privategpt python=3.11
conda activate privategpt
brew install poetry
poetry install --with ui,local

Group(s) not found: local (via --with), ui (via --with)
```
I want to use OpenAi.

What did I miss?

**Comment by pykeras** [comment]
The official documentation here: https://docs.privategpt.dev/installation/getting-started/installation specifies using `poetry install --extras "ui llms-ollama"` for installing PrivateGPT with the user interface (UI) and Ollama for the large language model (LLM).

Note: This replaces the previously mentioned `--with ui, local` syntax.

Additional Option for OpenAI:

If you intend to use OpenAI's LLM instead of Ollama, I believe you'll need to include the `llms-openai` extra during installation. Here's the updated command:

```bash
poetry install --extras "ui llms-openai"
```

This ensures you have both the UI and the necessary components for using OpenAI's LLM.

**Comment by mictadlo** [comment]
Thank you, it worked.

**Comment by JohnChristianIdul** [comment]
How about setting the PGT_Profile for this? did you use 
set PGPT_PROFILES=openai
