### ISSUE TITLE
privateGPT.py "Using embedded DuckDB with persistence: data will be stored in: db"

### ISSUE THREAD

**Issue by Naxica** [imartinez/privateGPT#295]
When running privateGPT.py after all other steps I get the message "Using embedded DuckDB with persistence: data will be stored in: db" just like I did with injest.py, then it exits without asking for a query.

Any ideas?

**Comment by imartinez** [comment]
The message is ok as the initial message, but it should not just exit after that. 

This is how it should look like:

```
Using embedded DuckDB with persistence: data will be stored in: db
gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 4505.45 MB
gptj_model_load: memory_size =   896.00 MB, n_mem = 57344
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285

Enter a query:
```

Do you get any kind of error?

**Comment by Naxica** [comment]
Thanks for the reply!  No it doesn't give an error, just closes for some reason...

**Comment by Naxica** [comment]
I've tried deleting everything and starting from scratch.  No errors, ingest goes fine, DB folder is created with index files and chroma

**Comment by PulpCattel** [comment]
Is it the same as https://github.com/imartinez/privateGPT/issues/281?

**Comment by Naxica** [comment]
Yes it is the same as #281.  Got the same error value returned as mentioned there.  Guess I'm just out of luck for using this?  Thank you for the link and help PulpCattel!

**Comment by Naxica** [comment]
Although my CPU does support AVX...

**Comment by ubuntinux** [comment]
> Although my CPU does support AVX...

Your CPU needs to support avx2 instructions, otherwise executing privateGPT script will give you the error: "Illegal instruction (core dumped)". Tested on two of my computers where one has an AMD CPU with avx instruction set (Illegal instruction (core dumped)), and on another INTEL CPU with avx and avx2 instruction set. (it worked).
Solutions: https://tech.amikelive.com/node-887/how-to-resolve-error-illegal-instruction-core-dumped-when-running-import-tensorflow-in-a-python-program/
