### ISSUE TITLE
CSV file is loading with just first row

### ISSUE THREAD

**Issue by ravindraprasad75** [imartinez/privateGPT#338]
When I tried ingesting csv file, only first record is loaded. Anyone has this issue?

<img width="759" alt="image" src="https://github.com/imartinez/privateGPT/assets/14846630/b6db6ecc-5d78-4e0b-8148-384f040bc72e">

After i run the privateGPT.py

<img width="1025" alt="image" src="https://github.com/imartinez/privateGPT/assets/14846630/fe47859c-7560-458d-aabe-56cd96db8ac4">

**Environment (please complete the following information):**
 - OS / hardware: [macOS Version 13.4 (22F66) / M1]
 - Python version [Python 3.10.0]

**Comment by PulpCattel** [comment]
Yeah I can reproduce. It was also mentioned in https://github.com/imartinez/privateGPT/issues/293 (and possibly a few other issues).

It's because of this line:

https://github.com/imartinez/privateGPT/blob/2f3aab9cfdc139f399387dbb90300d5a8bf8d2f1/ingest.py#L89

With `csv`, and maybe other formats too, the text is loaded into a list where each row is a separate document, therefore only the first row is returned.

**Comment by LiorZ** [comment]
I splitted the csv to one line per file .. it works find :)

**Comment by citron** [comment]
Same problem here but I won't split my csv in as many lines :)

**Comment by ravindraprasad75** [comment]
Created a Pull request #46
