### ISSUE TITLE
Mac m2 query slow

### ISSUE THREAD

**Issue by lvshuchengyin** [imartinez/privateGPT#402]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
I use a 8GB ggml model to ingest 611 MB epub files to gen 2.3GB db. And I query a question, it took 40 minutes to show the result. And I found the python process read 1.2TB data from disk.

**Expected behavior**
I have 24 GB memory in my mac mini, the model and db size is 10GB, then the process could hold all data to memory rather than  read data from disk so many time. And the cost time is too long.

**Environment (please complete the following information):**
 - OS / hardware: [e.g. macOS 12.6 / M2 mac mini 24GB memory]
 - Python version [e.g. 3.10.6]

**Comment by C0deXG** [comment]
same problem

**Comment by AlexTrykster** [comment]
I have experienced this same issue, but honestly i think it's a normal thing considering the initial phase of this project.
My way to bypass the problem is to load the files in smaller portions. I recently adopted this method and I think it is currently the only option that (not always) guarantees the most correct functioning.
Also, it might be an issue related to the LLM, so check if the performance of your mac fits properly for the LLM(it might be too big, for example). 
There is a challenging and way relatively long way to go before it’s an easy to run thing.
If you want to add more context, feel free to do that.

Have a great day!

**Comment by thomasjpatterson** [comment]
Having the same issue with an even smaller database. My db is 1.2 MB in size, my source documents are all PDFs that total less then 40MB in size.

My env file:
`PERSIST_DIRECTORY=db
MODEL_TYPE=LlamaCpp
MODEL_PATH=models/ggml-vic13b-q5_1.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000`

OS/Hardware: macOS 13.4.1 / M2 Pro 16GB RAM
Python: 3.11.1
![CleanShot 2023-07-03 at 14 41 38](https://github.com/imartinez/privateGPT/assets/8883279/a7adeebf-d93e-460a-b082-a9fb7c88906d)
