### ISSUE TITLE
Missing dep in requeriments.txt

### ISSUE THREAD

**Issue by rhoconlinux** [imartinez/privateGPT#498]
Just to report that 
dotenv
is not in the list of requeriments and hence it has to be installed manually.
Cheers,

**Comment by LaundroMat** [comment]
Just got bitten by this, don't forget the name of the package to install `python-dotenv`, so do a 

    pip install python-dotenv

**Comment by joseberlines** [comment]
after:
pip install python-dotenv 

the error persists.
(privateGPT) ➜  privateGPT git:(main) pip install python-dotenv
Requirement already satisfied: python-dotenv in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (1.0.0)
(privateGPT) ➜  privateGPT git:(main) /Users/jose/miniconda3/envs/privateGPT/bin/python /Users/jose/pyCode/privateGP
T/ingest.py
Traceback (most recent call last):
  File "/Users/jose/pyCode/privateGPT/ingest.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
(privateGPT) ➜  privateGPT git:(main)       

any idea why?

**Comment by imartinez** [comment]
I've reproduced the issue on a Windows laptop. The problem was not specifically dotenv, but the dependencies in general; there had been a problem installing requirements.txt. I followed the instructions at the bottom of the readme:

1. Install Visual Studio 2022.
2. Make sure the following components are selected:
  - Universal Windows Platform development
  - C++ CMake tools for Windows
3. Download the MinGW installer from the [MinGW website](https://sourceforge.net/projects/mingw/).
4. Run the installer and select the gcc component.

Then I still had problems running `py ingest.py`, but using `pythong ingest.py` it worked! 

Let me know if that solves your issue @joseberlines
