### ISSUE TITLE
Use falcon model in privategpt

### ISSUE THREAD

**Issue by mehrdad2000** [imartinez/privateGPT#630]
Hi how can i use Falcon model in privategpt?

https://huggingface.co/tiiuae/falcon-40b-instruct

Thanks

**Comment by HarihararamSriram** [comment]
I believe instead of GPT4All() llm you need to use the HuggingFacePipeline integration from LangChain that allows you to run HuggingFace Models locally.

```
`from langchain import HuggingFacePipeline

llm = HuggingFacePipeline.from_model_id(model_id="model-id of falcon", task="text-generation")
```
This will get you any LLM model from huggingface.

[https://python.langchain.com/en/latest/modules/models/llms/integrations/huggingface_pipelines.html](https://python.langchain.com/en/latest/modules/models/llms/integrations/huggingface_pipelines.html)

**Comment by pseudotensor** [comment]
Falcon 7B or 40B can be used with h2oGPT right now.  The demo without langchain is here: https://falcon.h2o.ai/

Try: https://github.com/h2oai/h2ogpt

You can use our versions from HF that have been instruct tuned:

https://huggingface.co/h2oai/h2ogpt-oig-oasst1-falcon-40b

h2oGPT will automatically use the correct prompt type.

These are Kaggle grandmaster versions for 7B:

https://huggingface.co/h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v2
https://huggingface.co/h2oai/h2ogpt-gm-oasst1-multilang-2048-falcon-7b

For these pass to `generate.py` also `--prompt_type=prompt_answer

Or for OASST falcon versions: https://huggingface.co/OpenAssistant

You  just pass to `generate.py` also `--prompt_type=open_assistant`

**Comment by mehrdad2000** [comment]
@pseudotensor how can i use these models [xlm-roberta-large-fa-qa](https://huggingface.co/SajjadAyoubi/xlm-roberta-large-fa-qa) and [bert-base-fa-qa](https://huggingface.co/SajjadAyoubi/bert-base-fa-qa/)  in h2oai?

**Comment by mehrdad2000** [comment]
@HarihararamSriram would you please explain more where should i add that line you mentioned?

**Comment by HarihararamSriram** [comment]
Okay, consider [Line 36](https://github.com/imartinez/privateGPT/blob/9d47d03d183685c675070d47ad3beb67446d6580/privateGPT.py#LL36C109-L36C109) of the given code. Here we load the GPT4All model into the variable `llm` using the GPT4All constructor.
Similarly, if you want to use Falcon instead of GPT4All, then the variable `llm` should be initialized with `HuggingFacePipeline.from_model_id(model_id="mtiiuae/falcon-7b", task="text-generation")` instead.
You can write code for another match-case for Falcon model
```python
match model_type:
        ...
        case "falcon":
            llm = `HuggingFacePipeline.from_model_id(model_id="mtiiuae/falcon-7b", task="text-generation")
```
This will get you the model from huggingface. Please refer this link for more information about this HuggingFacePipeline Integration.

Try and let me know how well it works.

**Comment by mehrdad2000** [comment]
@HarihararamSriram what should i set for ".env" for "MODEL_PATH"?
it take bin file, and in huggingface often there are more than single bin file like this: 
https://huggingface.co/tiiuae/falcon-40b-instruct/tree/main

any idea?

**Comment by robinliubin** [comment]
falcon works for me in this way:

**Comment by mehrdad2000** [comment]
@robinliubin Why your MODEL_PATH still refer to ggml-gpt4all-j-v1.3-groovy.bin?

**Comment by Yashs911** [comment]
@robinliubin But using HuggingFacePipeline won't train the model on private data?

**Comment by akashlinux10may** [comment]
https://github.com/akashlinux10may/AkashlinuxGPT

Here I have implemented is using falcon. You can refer here.

**Comment by jnkstr** [comment]
fer here.



> https://github.com/akashlinux10may/AkashlinuxGPT
> 
> Here I have implemented is using falcon. You can refer here.

No you are using a Google HuggingFace model.
Also everybody can see your Huggingface API Key in the Repo.

**Comment by akashlinux10may** [comment]
Thanks for replying and letting me about the API key. You are right there I used flan but same way I tried falcon also there 
repo id = tiiuae/falcon-7b-instruct

Only problem I am facing that it would also answer the questions out of the context.
