### ISSUE TITLE
GPT-J ERROR The prompt is4233tokens and the context window is2048!

### ISSUE THREAD

**Issue by denganhui** [imartinez/privateGPT#663]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
A clear and concise description of what the bug is and the steps to reproduce the behavior.

**Expected behavior**

**Environment (please complete the following information):**
 - OS / hardware: [e.g. macOS  M1]
 - Python version [e.g. 3.10]
- Other relevant information

**Additional context**
ERROR: The prompt size exceeds the context window size and cannot be processed.GPT-J ERROR: The prompt is4233tokens and the context window is2048!

**Comment by olepoeschl** [comment]
Same problem here. The problem occures at my setup when TARGET_SOURCE_CHUNKS is too high.

**Comment by owenpmckenna** [comment]
Currently GPT4All models have a limited context window. This is due to how they have been designed and trained and currently there is no fix that I know of (I did see a mention of a way around this but it involved training models in a certain way and I haven't seen any examples of it). It's discussed a bit elsewhere (for example [here](https://github.com/nomic-ai/gpt4all/issues/668)) and a in a few other issues in the same repository. 

The Context Size issue is not an issue with PrivateGPT, so this issue may be closed.
