### ISSUE TITLE
`loader` outside the loop?

### ISSUE THREAD

**Issue by linxule** [imartinez/privateGPT#75]
When running the command to ingest all the data, I encountered the following message:

UnboundLocalError: local variable 'loader' referenced before assignment

**Comment by gnscc** [comment]
That is because you have no (csv, txt, pdf) documents in the specified directory or the directory does not exist. Therefore, a loader is not assigned and is referenced trying to load a document that does not have. This problem will likely go away when ingestion.py accepts multiple documents in one ingestion and the loader assingment and reference will be in the same for-loop scope. Follow the updates on this issue on #74
