### ISSUE TITLE
What are the requirements on hardware for run this project?

### ISSUE THREAD

**Issue by pabl-o-ce** [imartinez/privateGPT#81]
Can you help giving more information about the requirements in hardware to test this project

particular what I need to in terms of hardware:
> Instructions for ingesting your own dataset

**Comment by Tobix99** [comment]
I've tried it on a VPS, Google Colab and a M1 Pro Mac and the best performance so far was the Mac.

I think the Mac has the best support, because LLama.cpp hast blast support for the ARM chip, but not for the VPS/Google Colab with a GPU.

In terms of RAM: At least 10Gb free RAM on your System, both 4GB files are loaded into RAM and the calulations for answering take up space too.

**Comment by GitEin11** [comment]
this should have been indicated on read me, I wasted effort only to find out that I can't ran it in my potato laptop hahaha

**Comment by d2rgaming-9000** [comment]
No there should be a maximum memory limit to run even in your potatoes laptop, by stringing processes into streams rather than bulk.

**Comment by digitalw00t** [comment]
It use to run fine on WSL2 with a 3060 8gb of vram.  But since all the pull requests and feature additions, now I'm just trying to get it to ingest and infer. Neither is working for me.
