### ISSUE TITLE
Incomplete response

### ISSUE THREAD

**Issue by ChrisBNECBT** [imartinez/privateGPT#836]
The response of a query is incomplete. _ChatGPT3.5_ allows users to prompt it to continue with the response in a new prompt and the team at _Oobabooga_ added a "Continue" button to their WebUI to do the same.

There is no way to continue lost response currently through a new prompt and splitting the prompts into smaller chunks resulted in a lost of context when responding.

I'm unsure whether this is a bug or missing feature and am wondering is there a **fix to allow a full response**.

I'm new to this.
![Screenshot 2023-07-09 at 08-47-17 ChatDocs](https://github.com/imartinez/privateGPT/assets/137929222/5f979540-29c3-403f-8795-55ed0fca811a)

**Comment by Eng-AliKazemi** [comment]
I have the same issue:
write a long story about Ukraine

> Answer (took 81.44 s.):

Ukraine is a country located in Eastern Europe, bordering Russia to the east and northeast, Belarus to the northwest, Poland and Slovakia to the west, Hungary, Romania, and Moldova to the south. The capital city of Ukraine is Kiev, which is also its largest city with over 2 million people living there.
Ukraine has a rich history dating back to ancient times when it was inhabited by various tribes such as the Scythians and Cimmerians. In the Middle Ages, it became part of the Kingdom of Galicia-Volhynia before being conquered by the Mongols in 1240. Later on, it came under the rule of Lithuania and Poland until it was annexed by Russia during the partitions of Poland in the late 18th century.
During World War II, Ukraine suffered greatly with over 6 million Ukrainians losing their lives due to famine caused by Soviet policies known as the Holodomor. After the war ended, Ukraine became a part of the Soviet Union until its collapse in 1991. Since then, it has been an independent country but continues to face challeng

Enter a query:

**Comment by remyderuysscher** [comment]
I second this, might be a technical issue such as time contraint or memory limitations? How can I investigate this?
