### ISSUE TITLE
Complexity in Installation

### ISSUE THREAD

**Issue by kumarankit999** [imartinez/privateGPT#85]
During Installation, Process is So Complex and Long-time taking, it should be not like this

**Comment by mali-tintash** [comment]
1. Make sure you have python3.10
2. Make sure to create python virtual environment (python -m venv <path to environment files>)
3. pip install -r requirements.txt
4. Download the required model files and put them in "models/" directory inside the main repo.
5. Rename example.env to .env

That's pretty much it. Long-time taking could be because of the models download.

**Comment by My-Inq** [comment]
All but 2 makes sense for newcomers.  Its never mentioned in repo instructions.

**Comment by mali-tintash** [comment]
It's always a good practice to isolate environments for different projects. It's not a must have, maybe that's why it was not mentioned explicitly

**Comment by My-Inq** [comment]
No disagreement, just have no experience with what that does.  I tried python ‘-m venv privategpt’ and it did nothing noticeable after I tried activating it.  Then tried  ‘source privategpt/bin/activate’ based on advice from GPT-4 but it doesnt seem to change anything as it doesn’t recognize any models or run.  Might be due to the recent quantization update breaking repos for many.  

Maybe using conda would work better?

**Comment by PierreVannier** [comment]
I'd mention the virtual env option in the install section.
Like "we strongly encourage you to" (but not mandatory) and explain which alternatives the user could use like venv, conda or poetry. (maybe a specific 4 or 5 lines later in the page for ppl who wants to follow that path)

**Comment by kumarankit999** [comment]
> 1. Make sure you have python3.10
> 2. Make sure to create python virtual environment (python -m venv )
> 3. pip install -r requirements.txt
> 4. Download the required model files and put them in "models/" directory inside the main repo.
> 5. Rename example.env to .env
> 
> That's pretty much it. Long-time taking could be because of the models download.

got it!
