### ISSUE TITLE
llama-cpp-python now supports GPU, privateGPT a lot faster now

### ISSUE THREAD

**Issue by darrinh** [imartinez/privateGPT#885]
ok, in privateGPT dir you can do:

pip uninstall -y llama-cpp-python
CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir

once that is done, modify privateGPT.py by adding:

model_n_gpu_layers = os.environ.get('MODEL_N_GPU_LAYERS')

underneath 'model_n_batch = int(os.environ.get('MODEL_N_BATCH',8))' line

also modify privateGPT.py  to include the gpu option:

llm = LlamaCpp(model_path=model_path, n_ctx=model_n_ctx, n_batch=model_n_batch, callbacks=callbacks, verbose=True,n_gpu_layers=model_n_gpu_layers)

modify the model in .env to change the model type and add gpu layers, etc, mine looks like:

PERSIST_DIRECTORY=db
MODEL_TYPE=LlamaCpp
MODEL_PATH=models/koala-7B.ggmlv3.q2_K.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=2048
MODEL_N_BATCH=1024
TARGET_SOURCE_CHUNKS=4
MODEL_N_GPU_LAYERS=100

When you start privateGPT now you should see:

Using embedded DuckDB with persistence: data will be stored in: db
ggml_init_cublas: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6
  Device 1: NVIDIA GeForce RTX 3060, compute capability 8.6
llama.cpp: loading model from models/koala-7B.ggmlv3.q2_K.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 10 (mostly Q2_K)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: using CUDA for GPU acceleration
ggml_cuda_set_main_device: using device 0 (NVIDIA GeForce RTX 3060) as main device
llama_model_load_internal: mem required  = 1713.10 MB (+ 1026.00 MB per state)
llama_model_load_internal: allocating batch_size x (512 kB + n_ctx x 128 B) = 384 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 32 repeating layers to GPU
llama_model_load_internal: offloading non-repeating layers to GPU
llama_model_load_internal: offloading v cache to GPU
llama_model_load_internal: offloading k cache to GPU
llama_model_load_internal: offloaded 35/35 layers to GPU
llama_model_load_internal: total VRAM used: 4042 MB
llama_new_context_with_model: kv self size  = 1024.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 

results:

Enter a query: how do we beat inflation?
Lower your costs, not your wages. Make more cars and semiconductors in America
llama_print_timings: load time = 3335.58 ms
llama_print_timings: sample time = 5.92 ms / 21 runs ( 0.28 ms per token, 3549.70 tokens per second)
llama_print_timings: prompt eval time = 3335.54 ms / 578 tokens ( 5.77 ms per token, 173.29 tokens per second)
llama_print_timings: eval time = 576.33 ms / 20 runs ( 28.82 ms per token, 34.70 tokens per second)
llama_print_timings: total time = 3937.84 ms

much, much faster and now a viable option for document qa.

cheers

**Comment by pawprint** [comment]
Could you be a bit more specific @darrinh about this line

`CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir`

I believe those first two are environment variables that need to be set so I tried

`SET CMAKE_ARGS="-DLLAMA_CUBLAS=on"`
and 
`SET FORCE_CMAKE=1`

but I'm still not getting the GPU enabled version. Any ideas?

**Comment by darrinh** [comment]
yep, you can run that command with '--verbose' to see if its detecting your cuda toolkit.  On Ubuntu 22.04 with the Cuda 12.2 tool kit, I did:

pip uninstall llama-cpp-python

CMAKE_ARGS="-DLLAMA_CUBLAS=on -DCUDA_PATH=/usr/local/cuda-12.2 -DCUDAToolkit_ROOT=/usr/local/cuda-12.2 -DCUDAToolkit_INCLUDE_DIR=/usr/local/cuda-12/include -DCUDAToolkit_LIBRARY_DIR=/usr/local/cuda-12.2/lib64" FORCE_CMAKE=1  pip install llama-cpp-python --no-cache-dir --verbose

IF it doesn't detect your cuda toolkit, it will just build for CPU.

**Comment by darrinh** [comment]
You'll need to edit the .env file to something similar to this:

PERSIST_DIRECTORY=db
MODEL_TYPE=LlamaCpp
MODEL_PATH=models/koala-7B.ggmlv3.q2_K.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=2048
MODEL_N_BATCH=1024
TARGET_SOURCE_CHUNKS=4
MODEL_N_GPU_LAYERS=100

**Comment by lamw** [comment]
Would the use of `CMAKE_ARGS="-DLLAMA_CLBLAST=on" FORCE_CMAKE=1 pip install llama-cpp-python`[1] also work to support non-NVIDIA GPU (e.g. Intel iGPU)? I was hoping the implementation could be GPU-agnostics but from the online searches I've found, they seem tied to CUDA and I wasn't sure if the work Intel was doing w/PyTorch Extension[2] or the use of CLBAST would allow my Intel iGPU to be used for processing

1 - [https://github.com/abetlen/llama-cpp-python/blob/main/README.md#installation-with-openblas--cublas--clblast--metal](https://github.com/abetlen/llama-cpp-python/blob/main/README.md#installation-with-openblas--cublas--clblast--metal)
2 - https://towardsdatascience.com/pytorch-stable-diffusion-using-hugging-face-and-intel-arc-77010e9eead6

**Comment by Amine-Kamoun** [comment]
Thank you for the tip!

Install went fine on my side but I'm getting this error that seems to be linked to memory : 

Enter a query: Which indices are mentioned in the document?
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 28728784, available 10485760)
Traceback (most recent call last):
  File "Y:\Copilot\privateGPT\privateGPT.py", line 84, in <module>
    main()
  File "Y:\Copilot\privateGPT\privateGPT.py", line 55, in main
    res = qa(query)
  File "Y:\Copilot\oobabooga_windows\installer_files\env\lib\site-packages\langchain\chains\base.py", line 243, in __call__
    raise e
  

I have a 3090 with 24gb of VRAM / 64gb of RAM. Is that because of the size of the chunks of the vectorized doucement ? Any idea ? Thank you

ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6
llama.cpp: loading model from models/koala-7B.ggmlv3.q2_K.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 4096
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 1.0e-06
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 10 (mostly Q2_K)
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  =  567.10 MB (+ 2048.00 MB per state)
llama_model_load_internal: allocating batch_size x (512 kB + n_ctx x 128 B) = 512 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 32 repeating layers to GPU
llama_model_load_internal: offloading non-repeating layers to GPU
llama_model_load_internal: offloading v cache to GPU
llama_model_load_internal: offloading k cache to GPU
llama_model_load_internal: offloaded 35/35 layers to GPU
llama_model_load_internal: total VRAM used: 5192 MB
llama_new_context_with_model: kv self size  = 2048.00 MB

**Comment by pawprint** [comment]
OK finally got it working on Windows 11.  For others here is what you need to do.

First you need to install the cuda toolkit - from Nvidia. For Windows 11 I used the latest version 12.2 at the time of writing. After install make sure you re-open the Visual Studio developer shell.

Then you need to uninstall and re-install torch (so that you can for it to include cuda) in your privateGPT env.

`pip uninstall torch`
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

Then after doing that you can proceed as above:

`SET CMAKE_ARGS="-DLLAMA_CUBLAS=on"`
`SET FORCE_CMAKE=1`
and finally

`pip uninstall -y llama-cpp-python`
`pip install llama-cpp-python --no-cache-dir --verbose`

**Comment by Komal-99** [comment]
Hi, @darrinh  I made the necessary changes in the file for GPU acceleration but now while loading the model facing 1 validation error.
![image](https://github.com/imartinez/privateGPT/assets/74819092/4602bd63-5405-40ed-a2f3-be5c389758bc)
 Could you suggest any solution to this?

**Comment by darrinh** [comment]
That error is usually because it can't find the model in the path provided or its not the correct format. llama-cpp support the GGUF model type now -> https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF

**Comment by Komal-99** [comment]
Thankyou, I will try this out

**Comment by DenizK7** [comment]
when i did all steps and after try to install llamacpp this error occur all the time 

  _*** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects_

I'm currently working on windows 11

**Comment by sujata-appiot** [comment]
@darrinh , I executed the steps you showed here & tried with the same model **koala-7B.ggmlv3.q2_K.bin**
I get this error
`pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: models/koala-7B.ggmlv3.q2_K.bin. Received error  (type=value_error)
`

It also does not work with GGUF model.
Anything you can suggest?

**Comment by thanhtantran** [comment]
> llama_model_load_internal: offloaded 35/35 layers to GPU

how to increate the number of layers offloaded to GPU?
