### ISSUE TITLE
Can't install llama-cpp-python from requirement text

### ISSUE THREAD

**Issue by AAbdullah1918** [imartinez/privateGPT#958]
### Discussed in https://github.com/imartinez/privateGPT/discussions/948

<div type='discussions-op-text'>

<sup>Originally posted by **AAbdullah1918** August 13, 2023</sup>
I want to use eachadea/ggml-vicuna-13b-1.1 as my LLM model. I made the appropriate changes to the .env file but when I run the pip3 install -r requirements.txt command in cmd, it gives me the following error:
`  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.`

`  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
  Building wheel for hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error`

` Building wheel for hnswlib (pyproject.toml) did not run successfully.`
`Failed to build llama-cpp-python hnswlib
ERROR: Could not build wheels for llama-cpp-python, hnswlib, which is required to install pyproject.toml-based projects`

I was following this tutorial on how to install PrivateGPT, if that helps: [https://www.youtube.com/watch?v=A3F5riM5BNE&list=PLDlsxP8Mhcy3Gq9bNDhNthE6h4fzTa1YE&index=1](url)

How could I resolve this error? Any help is appreciated. Thanks</div>

**Comment by bwithai** [comment]
Dear @AAbdullah1918 thanks to highlight this issue. These errors are usually related to compiling C/C++ code as part of the package installation process.

### **llama-cpp-python:**
There is an issue with configuring CMake for this package. It's complaining about not finding a C compiler and is asking for you to set the CC environment variable or update the CMAKE_C_COMPILER cache entry.

### **chroma-hnswlib:**
This package is failing to build because it requires C++11 support, but the build environment does not seem to have that support. The error message suggests that the minimum supported C++ version is C++11.


## **How to resolve this issue**

On Debian-based systems (e.g., Ubuntu)
`sudo apt-get update`
`sudo apt-get install build-essential`

if chroma-hnswlib is still failing due to issues related to the C++ compilation process.
`sudo apt-get install python3-dev`

**Try Installing Packages Again**
