### ISSUE TITLE
Default Python Version

### ISSUE THREAD

**Issue by cbassoc3265** [imartinez/privateGPT#969]
I see that you need Python 3.10 or later installed because earlier versions of Python will not compile. My OS (Ubuntu 20.04.6 LTS) has Python3.8 as the default and when I install Python3.11 and change the default from 3.8 to 3.11 it breaks my system. I can have version 3.11 installed and I can call it and use it.

Is there a way to force the script to use 3.11 and NOT the default 3.8?

**Comment by cbassoc3265** [comment]
I am assuming you would only have to do this when calling the ingest.py and the privateGPT.py scripts. Is it as simple as running "python3.11 ingest.py" instead of "python ingest.py" ??

**Comment by cbassoc3265** [comment]
I am also assuming I would install pip3 and use the command "pip3 install -r requirements.txt" ???

**Comment by stijndcl** [comment]
If you're using pip then indeed use `python3.11` instead of `python3`, and `python3.11 -m pip` (I'm pretty sure `pip3` would use your system python).

If using Poetry you can tell it which version you want to use with `poetry env use 3.10`.

> when I install Python3.11 and change the default from 3.8 to 3.11 it breaks my system.
On another note I recommend using `pyenv` to manage multiple versions to avoid ending up in this situation: https://github.com/pyenv/pyenv

Allows you to change your global version to whatever you want, and `python3` and `pip3` will point to the ones you choose.
