### ISSUE TITLE
how come is this private?

### ISSUE THREAD

**Issue by K-tang-mkv** [imartinez/privateGPT#98]
I'm confued about the private, I mean when you download the pretrained llm weights on your local machine, and then use your private data to finetune, and the whole process is definitely private, so what's the difference from this repo.

**Comment by outjet** [comment]
What are you asking?

**Comment by K-tang-mkv** [comment]
@outjet 
I mean why this repo say it can interact with llm privately. What I know is as long as you use gpt locally, it's definitely private, so what is the difference from this repo.

**Comment by alxspiker** [comment]
Most other repos use APIs for inference and connect their data to the internet.

**Comment by tuananh** [comment]
meaning you can run this completely in an airgapped environment?

**Comment by geeeezx** [comment]
I don't get it either......

**Comment by topcheese** [comment]
Nothing to really be confused about, private means private.  It uses GPT4All, so that's one thing that makes it private, and couple that with some additional tools to help facilitate the process.
I'm assuming it's still all local ... hence the title.
I haven't checked it out yet, but have checked out GPT4All.

**Comment by pboethig2** [comment]
its a good name, for a project doesnt make use of the single point of ChatGPT. Thanx for that

**Comment by K-tang-mkv** [comment]
So for all the projects that use llm checkpoint locally and use local data can be said private, right?

**Comment by K-tang-mkv** [comment]
I forked a project called [miniGPT4](https://github.com/K-tang-mkv/MiniGPT-4), and then I deploy on my local machine and use it for myself without internet, can I said this is private?

**Comment by uogbuji** [comment]
@andyjphu nailed it. Anyone was free to make a framework allowing any generative pretrained transformer (GPT) to be used privately. Anyone would have been entitled to call it privateGPT. These guys just went ahead and did what anyone was able to do. It's useful work that many others have put to use. Having a good name for it is part of what's enabled others to find it & put it to use.

There need be no confusion. All is well.

**Comment by pseudotensor** [comment]
The benefits of this repo are:
* CPU-based LLMs (reach mac/windows users who couldn't otherwise run on GPU)
* LangChain integration for document question/answer with persistent db
* Embedding is also local, no need to go to OpenAI as had been common for langchain demos

I think privateGPT is great.  Check out our version, which includes full UI and GPU support, among everything else privateGPT has: https://github.com/h2oai/h2ogpt .

**Comment by uogbuji** [comment]
> I think privateGPT is great. Check out our version, which includes full UI and GPU support, among everything else privateGPT has: https://github.com/h2oai/h2ogpt .

This looks cool, but I do want to point out that privateGPT did support GPU out of the box, for me.

**Comment by nickion** [comment]
> The benefits of this repo are:
> 
> * CPU-based LLMs (reach mac/windows users who couldn't otherwise run on GPU)
> * LangChain integration for document question/answer with persistent db
> * Embedding is also local, no need to go to OpenAI as had been common for langchain demos
> 
> I think privateGPT is great. Check out our version, which includes full UI and GPU support, among everything else privateGPT has: https://github.com/h2oai/h2ogpt .

If used with the same model, e.g. ggml-vic13b-q5_1, would yours also be likely to have the same faults? 

I loaded a file with C code, and while it clearly has knowledge of code and answered one query well, it was wildly wrong in its answer to another simple question, and surprisingly, English grammar was also incorrect in using `it's` for a possessive instead of `its`. I then loaded a modified version of the default document and asked it to compare the two, and it was completely wrong, saying that one text document was in json format while the other was legacy. This was actually drawing from documentation in a user guide for one of our software products., and baffling as to what in the question took it into that.  Wondering if this would be purely down to the language model or whether it could be in the design of the GPT wrapper as well.

**Comment by pseudotensor** [comment]
@nickion The main benefits of h2oGPT vs. privateGPT are:
* Rely upon instruct-tuned models, so avoiding wasting context on few-shot examples for Q/A.
* Many of the segfaults or other ctx issues people see is related to context filling up.  That doesn't happen in h2oGPT, at least I tried default `ggml-gpt4all-j-v1.3-groovy.bin` model that also failed for me without improvements to usage.
* UI control over everything
* chat import-export and memory
* client API
* image support
among other things...

What won't change with h2oGPT are bad language behaviors with the model.
